### ISSUE TITLE
Same way to use -std modifier in the examples

### ISSUE THREAD

**Issue by Canario0** [ismtabo/cpp_tutorial#12]
Why we dont use the same way to use ```-std``` modifier in the example. 
We have this:
```
g++ -std=c++0x helloworld.cpp -o HelloWorld
clang++ -std=c++11 -stdlib=libc++ helloworld.cpp -o HelloWorld
```
I propose to use -std=c++11 in the g++ example, like this:
```
g++ -std=c++11 helloworld.cpp -o HelloWorld
clang++ -std=c++11 -stdlib=libc++ helloworld.cpp -o HelloWorld
```

**Comment by ismtabo** [comment]
I don't get it. Do you think it is relevant?

**Comment by Canario0** [comment]
@ismtabo Yes, i think it is relevan. They could get confuse

**Comment by ismtabo** [comment]
@Canario0 ok. Assigned to you.
